### ISSUE TITLE
Disable for mobile

### ISSUE THREAD

**Issue by kaless1n** [shiryel/saos#29]
I would like an option to disable animations for mobile devices.

**Comment by danielclough** [comment]
What about using media queries to disable?

For example:

```css
@media (min-width: 900px) {
    @keyframes -global-from-left {
        0% {
            transform: rotateX(50deg) translateX(-200vw) skewX(-50deg);
            opacity: 0;
        }
        100% {
            transform: rotateX(0deg) translateX(0) skewX(0deg);
            opacity: 1;
        }
    }
```
